version: "3.7"
services:
  # run with docker-compose run --rm --service-ports postgis
  postgis:
    image: "postgis-server:latest"
    container_name: ${POSTGIS_HOSTNAME}
    networks: 
      - gis
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ${HOST_DATABASE_LOCATION}:/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PGDATA=/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  preprocessing:
    image: "postgis-client:latest"
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ./../../processing/preprocessing.sh:/preprocessing.sh:ro
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - DATABASE_NAME=${DATABASE_NAME}
      - LOCALHOST=${LOCALHOST}
    entrypoint: bash
    command: /preprocessing.sh

  slice:
    image: "postgis-client:latest"
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ${IMPORT_PATH}:/tmp/data
      - ${SOURCE_PATH}${SOURCE_FILE}:/tmp/osmdata.osm.pbf:ro
      - ./../../processing/slice.sh:/slice.sh:ro
      - ${POLY_PATH}:/tmp/poly
    environment:
      - LOCALHOST=${LOCALHOST}
      - LEFT=9.39
      - BOTTOM=46.67
      - RIGHT=12.04
      - TOP=47.81
      - POLY_FILES=${POLY_FILES}  # comment out this line to use bbox slicing
      - OUT_FILE=${IMPORT_FILE}
      - SOURCE_FILE=${SOURCE_FILE}
      - MERGE_FILES=${MERGE_FILES}
    entrypoint: bash
    command: /slice.sh

  import:
    image: "postgis-client:latest"
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ${IMPORT_PATH}${IMPORT_FILE}:/tmp/osmdata.osm.pbf:ro
      - ${IMPOSM_MAPPING}:/tmp/mapping.yaml:ro
      - ./../../processing/import.sh:/import.sh:ro
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - DATABASE_NAME=${DATABASE_NAME}
      - LOCALHOST=${LOCALHOST}
    entrypoint: bash
    command: /import.sh

  postprocessing:
    image: "postgis-client:latest"
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ./../../processing/postprocessing.sh:/postprocessing.sh:ro
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - DATABASE_NAME=${DATABASE_NAME}
    entrypoint: bash
    command: /postprocessing.sh

  shp_download:
    image: "postgis-client:latest"
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ${IMPORT_PATH}:/tmp/data
      - ./../../processing/shp_download.sh:/shp_download.sh:ro
    environment:
      - LOCALHOST=${LOCALHOST}
    entrypoint: bash
    command: /shp_download.sh    

  shp_import:
    image: "postgis-client:latest"
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ${IMPORT_PATH}:/tmp
      - ./../../processing/shp_import.sh:/shp_import.sh:ro
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - SHAPE_DATABASE_NAME=${SHAPE_DATABASE_NAME}
      - LOCALHOST=${LOCALHOST}
    entrypoint: bash
    command: /shp_import.sh

  shp_postprocessing:
    image: "postgis-client:latest"
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ./../../processing/shp_postprocessing.sh:/shp_postprocessing.sh:ro
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - SHAPE_DATABASE_NAME=${SHAPE_DATABASE_NAME}
      - LOCALHOST=${LOCALHOST}
    entrypoint: bash
    command: /shp_postprocessing.sh

  shp_water:
    image: "postgis-client:latest"
    depends_on:
      - postgis
    networks: 
      - gis
    volumes:
      - ${IMPORT_PATH}:/tmp
      - ./../../processing/shp_water.sh:/shp_water.sh:ro
    environment:
      - POSTGIS_HOSTNAME=${POSTGIS_HOSTNAME}
      - POSTGIS_USER=${POSTGIS_USER}
      - SHAPE_DATABASE_NAME=${SHAPE_DATABASE_NAME}
      - LOCALHOST=${LOCALHOST}
      - SHAPEFILE=simplified-water-polygons-split-3857/simplified_water_polygons
      - GRID=grid_coarse
      - RESOLUTION=2048
      - OUTPUT=water_gen
      - INITIALZOOM=3
      - ZOOMLEVELS=4
    entrypoint: bash
    command: /shp_water.sh    

networks:
  gis:
    name: gis
